### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by ttaoREtw** [lab4d-org/lab4d#1]
Thank you for your outstanding work!
I would like to inquire about the ETA for the code release, if you don't mind.

**Comment by gengshan-y** [comment]
Apologize for the late reply, we plan to release the alpha version this coming Sun.

**Comment by ttaoREtw** [comment]
Hi, I was wondering if there were any updates?

**Comment by gengshan-y** [comment]
The code is released! thanks for waiting

**Comment by ttaoREtw** [comment]
Thanks for updating!
Do you mind to reveal the plan for a more comprehensive step-by-step README?
