### ISSUE TITLE
[BUG] error: parameter packs not expanded with '...'

### ISSUE THREAD

**Issue by ttaoREtw** [lab4d-org/lab4d#10]
Got a compiling error: `/home/ttao/miniconda3/envs/lab4d/x86_64-conda-linux-gnu/include/c++/11.4.0/bits/std_function.h:435:145: error: parameter packs not expanded with '...'`.

It can be resolved by changing `gcc_linux-64=11` to `gcc_linux-64=10` in `environment.yml` (change gxx to 10, too).

```
system: ubuntu 22.04
nvcc: 11.7, V11.7.64
```

Similar issue: https://github.com/NVlabs/instant-ngp/issues/119

**Comment by gengshan-y** [comment]
Thanks for the report and fix. I did not observe the same error on the machines I tested. As a general fix was unclear (in the instant-ngp thread), I will close it for now. We can change to `gcc_linux-64=10` if more people report the same problem.
