### ISSUE TITLE
Issue about gradio app when following the tracking module instructions

### ISSUE THREAD

**Issue by Xin-97** [lab4d-org/lab4d#13]
Hi, thanks for your great work, I have a problem when build the environment of lab4d, as shown below.
![Screenshot from 2023-08-03 16-35-25](https://github.com/lab4d-org/lab4d/assets/110981717/152f9ebe-138c-4478-9ac0-0910e95c3cfb)

Have you also encountered this problem? Thanks!

**Comment by gengshan-y** [comment]
Hi, this is not expected, did you follow the instructions [here](https://lab4d-org.github.io/lab4d/get_started/)?

**Comment by Xin-97** [comment]
Hi, I have fixed this problem, I guess it may be because of the Cuda version. I have found another question, when I try to preprocess the data like below, I do not find the 'Add mask' button.
![Screenshot from 2023-08-03 22-54-49](https://github.com/lab4d-org/lab4d/assets/110981717/10b40569-3b49-4a95-b086-9d98be52f678)

**Comment by gengshan-y** [comment]
Is this after clicking load videos? Here is the expected output
![image](https://github.com/lab4d-org/lab4d/assets/13134872/8ff046aa-837a-4e05-b0a9-abc9ba935e0f)

If it got stuck after clicking load videos, it might be a vs-code related [issue](https://lab4d-org.github.io/lab4d/qa.html#data-pre-processing)

**Comment by Xin-97** [comment]
Hi, I also got stuck when loading video, I cannot select a video from the bottom carousel. So I upload a video from the local. I run the preprocess coda at terminal so I am not sure how to fix it. I have try to kill the script and re-run it many times but it still cannot work.

**Comment by gengshan-y** [comment]
I don't understand what it means by "cannot select a video from the bottom". It appears ineffective to communicate in this way. Can you follow [the bug/issue tracker](https://raw.githubusercontent.com/lab4d-org/lab4d/main/.github/ISSUE_TEMPLATE/bug-issue-report.md) to describe the steps and the outcome?

Just to clarify, in order to preprocess the demo car video, nothing needs to be uploaded. This is the way it works (see this [tutorial](https://lab4d-org.github.io/lab4d/tutorials/preprocessing.html)) for some context:

1. Run `python scripts/run_preprocess.py car-turnaround-2 other "0"`
2. A link will be prompted in the terminal after flow filtering. Click that link, and you'll be redirected to the modified track-anything gradio app.
3. Follow the instructions on the top to segment the object.

**Comment by Xin-97** [comment]
Hi, sorry I did not make it clear. Please help to check the below screenshot, I cannot select the example video to upload it. So I cannot continue following the instructions. When I click the 'Click to Upload' button, I can only upload videos from local.
![Screenshot from 2023-08-05 17-31-00](https://github.com/lab4d-org/lab4d/assets/110981717/ca3a2002-03e0-4f98-b898-d0431961333f)

**Comment by gengshan-y** [comment]
This screenshot looks normal. To clarify, *users are supposed to upload videos locally*. If "drop video here" message is causing the confusion, please ignore it for now and we need to remove it.

**Comment by Xin-97** [comment]
Hi, thanks for the clarification. There is still no reaction after I press the 'Load Video' button and I have killed the script and re-run it several times. 
![Screenshot from 2023-08-06 14-48-47](https://github.com/lab4d-org/lab4d/assets/110981717/c982d148-ee52-42c6-ad55-ba3ab9faa82a)

**Comment by gengshan-y** [comment]
I see. In my experience, refreshing the page and do it again (click the bottom video>>click load videos) worked. 

If that does not work, could you try killing all vscode processes and do it again? e.g.
```pkill -f vscode```
 which terminates processes whose command line arguments match `vscode`.

**Comment by Xin-97** [comment]
Hi, it still did not work. And I tried to open the local URL or the public URL when using a remote server. Both ways did not work. I cannot select the bottom video. And clicking load videos has no reactions. It is really weird. Do you have any other suggestions? Thanks.

**Comment by gengshan-y** [comment]
This is strange. We need more information to look into this, at least to reproduce the behavior.

Could you do the following?
1. Activate the lab4d environment, and run `conda list`. Attach the output in a separate file
2. Run `python preprocess/third_party/Track-Anything/app.py car-turnaround-2`. Report the output from the console, and the steps you took on the web interface.

**Comment by Xin-97** [comment]
Hi, please check the lab4d environment as attached. 

I run `python preprocess/third_party/Track-Anything/app.py car-turnaround-2`, and the output is shown below. I still cannot load videos on the web interface as before (I cannot select the bottom video and can only upload video locally, and clicking 'load video' has no reaction). 
[lab4d.txt](https://github.com/lab4d-org/lab4d/files/12273346/lab4d.txt)

![Screenshot from 2023-08-07 15-15-48](https://github.com/lab4d-org/lab4d/assets/110981717/77319411-b893-45fa-b5e3-38d46428b81f)

**Comment by gengshan-y** [comment]
Hi, I recorded a [video](https://github.com/lab4d-org/lab4d/assets/13134872/06631054-8623-4c9e-98af-f1b186d5a184) of running track-anything in lab4d, is that consistent with what you observed?

Besides, after checking the output `conda list`, I found the `gradio-client` version is different. Hereis the one I have after installing following the instruction.
```
gradio                    3.28.3                   pypi_0    pypi
gradio-client             0.1.4                    pypi_0    pypi
```

**Comment by Xin-97** [comment]
Hi, thanks for your effort. I have reinstalled the right version of `gradio-client`, but it still does not work as you recorded. I also record a video to show what I see on gradio app. Please check 
[Screencast from 09-08-2023 16%3A04%3A21.webm](https://github.com/lab4d-org/lab4d/assets/110981717/ef2533c5-8705-450b-b433-5b69a8544f09), sorry for that I do not know why the pointer cannot be shown properly in the screencast. 

Different from your recording, when I click the center (Drop video here or click to upload), it will open the local file rather than select the example video at the bottom. Although I upload video from local files, there is no reaction after I click the 'Load Video' button.

**Comment by gengshan-y** [comment]
It seems there is still some confusion in our communication. Again, this app does not allow "Drop video here or click to upload" You are only supposed to select from the bottom carousel, which lists the videos in the folder `database/raw/$seqname`.

It would be helpful to know what happens after clicking the bottom video
<img width="305" alt="image" src="https://github.com/lab4d-org/lab4d/assets/13134872/8a50b639-dbe3-458e-9a6b-57eec70b1cf3">

**Comment by Xin-97** [comment]
Yes, I have seen that you upload the bottom video in your video recording. I also tried to upload the bottom video in my recording (it may be not obvious because of the mouse pointer. When I click the bottom video, its bounding box will be orange). So nothing happens after clicking the bottom video, only the color of its bounding box change. I click the 'Load Video' after clicking the bottom video and also nothing happens (No video uploaded as shown in your recording).

I saw you click the "Drop video here or click to upload" first before clicking the bottom video in your recorded video, so I may misunderstand it.

**Comment by gengshan-y** [comment]
No worries, did any error pop up in the terminal after clicking "load video"? 

It still seems to be a gradio GUI / network issue. This can be verified and isolated by running the official [Track-anything](https://github.com/gaomingqi/Track-Anything) and checking whether the "load video" button works there.

Looping @neeharperi in, in case he has ideas.

**Comment by Xin-97** [comment]
Hi, I just tried the official Track-anything, and there is still nothing happens after clicking the bottom videos. And there is no error in the terminal during the operation on gradio gui. Do you have any suggestions? @neeharperi, thanks!

**Comment by neeharperi** [comment]
Can you create a **new** conda environment and only install Track-Anything. Please try their demo by clicking on one of the examples videos in the bottom carousel. I still believe this is an issue with the environment.

**Comment by Xin-97** [comment]
Hi, thanks for your suggestion, I create a new conda environment for Track-Anything then it worked. I found in my lab4d environment, the version of `gradio` is 3.28.3, and in the new environment for Track-Anything, the version is 3.39.0. So I reinstall `gradio==3.39.0` and it works. Thanks for your help @gengshan-y @neeharperi .
