### ISSUE TITLE
Is there any figure or abstract for the pipeline used in this repo?

### ISSUE THREAD

**Issue by zz7379** [lab4d-org/lab4d#15]
Is there any figure or abstract for the pipeline used in this repo?
I am a little confused about what method does this repo use.

**Comment by gengshan-y** [comment]
For an introduction to the pipeline, please refer to [banmo](https://banmo-www.github.io/). 

The default training config tries to match [rac](https://gengshan-y.github.io/rac-www/). There are some extensions (e.g., dino-v2 features) to make it more generic, but the performance on humans and quadrupeds is similar to rac. 

There are flags defined in [`lab4d/config.py`](https://github.com/lab4d-org/lab4d/blob/main/lab4d/config.py) to change types of supervision and motion fields, which should allow one to switch between methods.

**Comment by zz7379** [comment]
Thanks a lot! I'll check it
