### ISSUE TITLE
Root object pose visualization

### ISSUE THREAD

**Issue by ttaoREtw** [lab4d-org/lab4d#2]
First of all, very appreciate your time and effort!! This work is pretty solid.
Just have one quick question: How can I visualize the root object poses during optimization (epoch 0~N) as in BANMo repo?

<img width="566" alt="image" src="https://github.com/lab4d-org/lab4d/assets/41298349/69a68174-b236-4867-9d2b-f6991edd0298">

**Comment by gengshan-y** [comment]
Hi, there is a [script](https://gist.github.com/gengshan-y/7e184d1a101b8918610f23f4fb497589) to do so in the next commit in a few days.

**Comment by ttaoREtw** [comment]
Thanks! It works.
Just so you know that `pyrender` is out of the original `environment.yml`.
