### ISSUE TITLE
Error when running "scripts/run_preprocess.py" with custom video

### ISSUE THREAD

**Issue by DenisKochetov** [lab4d-org/lab4d#20]
**Tries to download data plus deletes folder with custom video**
When I try to preprocess custom video, its folder gets deleted and the programme is waiting for me to input url. 

**To Reproduce**
1. Create folder  database/vid_data/$seqname
2. Run python scripts/run_preprocess.py $seqname cat quad "0"
3. Get your folder deleted

**Expected behavior**
Preprocessing without an attempt to download the video. 

**Screenshots**
![image](https://github.com/lab4d-org/lab4d/assets/57500456/e4aa82b0-ae61-4888-ae2d-779922d69682)

![image](https://github.com/lab4d-org/lab4d/assets/57500456/798feefb-c197-4c80-81e7-3e13f7431fee)

**Additional context**
I fixed it with extra check for directory existence.

**Comment by gengshan-y** [comment]
Merged, thanks!
