### ISSUE TITLE
[Question] Possibility of videos with motion-corresponding bone outputs similar to RAC in Lab4D

### ISSUE THREAD

**Issue by kokist** [lab4d-org/lab4d#26]
Hi @gengshan-y .
Thank you for the great work.
In Lab4D, is it possible to produce videos similar to RAC and their corresponding bone outputs?
Looking forward to your response.

**Comment by gengshan-y** [comment]
Hi. There is a ppr branch that implements mesh rendering with bones (instructions [here](https://github.com/gengshan-y/ppr#visualization)). We plan to merge it once more testing is done. For a quick solution, I would recommend using the ppr branch directly.

It would also be possible to port the [pyrender wrapper](https://github.com/lab4d-org/lab4d/blob/ppr/lab4d/utils/pyrender_wrapper.py) and [mesh renderer](https://github.com/lab4d-org/lab4d/blob/ppr/lab4d/render_mesh.py) code directly with some effort.

**Comment by kokist** [comment]
Thank you for your response.
I'll give the ppr branch a try!
Looking forward to the merge!
