### ISSUE TITLE
Differences between ppr branch and the main branch

### ISSUE THREAD

**Issue by ChaoyueSong** [lab4d-org/lab4d#27]
Hi Gengshan, thanks for your great work!

I have some questions about the differences between ppr branch and the main branch.
1. I found that the design of delta_skin in ppr branch and the main branch is different. You remove the time_embedding and add the normalization of xyz_bone in ppr branch. So what is the advantage of this design? 
2. And is the loss weight setting in ppr branch more advanced than the main branch? 
Thanks!

**Comment by gengshan-y** [comment]
Hi Chaoyue, sorry for the late reply. The main branch is similar to BANMo's implementation: delta_skin_t = f(X_t,code_t). The PPR branch represents delta skinning weights as a function of its local bone coordinates: delta_skin = f(X_bone-1, ...X_bone-B), similar to [A-NeRF](https://arxiv.org/pdf/2102.06199.pdf). The ones in the PPR branch are more articulation-dependent / less time-dependent and should generalize better.

The PPR weighting should be better in general. But I did observe it is less stable. Still need some time to verify before a merge.

**Comment by ChaoyueSong** [comment]
Hi Gengshan, thanks for your explanation!
