### ISSUE TITLE
Track-Anything commit in PPR branch

### ISSUE THREAD

**Issue by lxxue** [lab4d-org/lab4d#28]
Hi Gengshan, thanks for the series of works and sharing them together in a single repository.

I am trying out the PPR branch and found that the [Track-Anything commit](https://github.com/gengshan-y/Track-Anything/tree/dc25a7aec2ab7d46bfd545164a8cb879185a4cdf) might be a bit outdated: the `track_anything_cli.py` file is missing.

Updated to the [current commit ](https://github.com/gengshan-y/Track-Anything/tree/73778091905626aaca2d6fa50fe2f0e11bc49403) seems to solve the problem.

**Comment by gengshan-y** [comment]
Thanks! This has been fixed now.
