### ISSUE TITLE
[Bug/issue] Rendering meshes from "field2cam"

### ISSUE THREAD

**Issue by thomasdwlk** [lab4d-org/lab4d#31]
Hi, 
thank you for sharing this nice project.
I was wondering, after training and rendering from tutorial RAC (reconstructing categories), is it possible to render the exported meshes "fg-xxxxx.obj" such that is match in position the other rendering visualizations (such as normal.mp4, rgb.mp4) . I see the "field2cam" matrices in fg-motion.json, and the world to camera (00.npy) and object to camera (01.npy). However, I don't see in the code where to use these transformations to do so.
Thank you,

**Comment by gengshan-y** [comment]
Hi, the ppr branch has functions to do so (see [this](https://github.com/lab4d-org/lab4d/issues/26#issuecomment-1774129539)), but is not compatible with the RAC checkpoints. You might consider re-training RAC with the ppr branch, or porting the mesh rendering code from ppr to the master branch. Hope this helps.
