### ISSUE TITLE
[Question] Volume rendering of depth and normal

### ISSUE THREAD

**Issue by lxxue** [lab4d-org/lab4d#32]
Hi Gengshan, 

I wonder if the PPR branch has some scripts for volume rendering the depth and normal maps for the full image? The results rendered from meshes contain holes so I want a volume rendering version.

**Comment by gengshan-y** [comment]
Hi, you may use the same scripts [here](https://lab4d-org.github.io/lab4d/tutorials/single_video_cat.html#rendering-after-training) that renders depth/normal into the same folder as other quantities. The holes in the mesh is usually a visibility estimation issue, perhaps try `--vis_thresh -10`?

**Comment by lxxue** [comment]
Thank you for the quick reply. Changing the `vis_thresh` did help a lot!
