### ISSUE TITLE
[issue] Is it possible to input a camera external reference? I get it from colmap.

### ISSUE THREAD

**Issue by limaolin2017** [lab4d-org/lab4d#44]
First of all, thank you for your contribution.

I got the file of camera argues from colmap, is it possible to use it as input to lab4d?

**Comment by gengshan-y** [comment]
Hi, sorry for the late response

To use the colmap camera extrinsics, you may overwrite the camera files located at `Cameras/Full-Resolution/$seqname/%02d.npy` following [this format explained here](https://lab4d-org.github.io/lab4d/tutorials/arbitrary_video.html#download-preprocessed-data) (also see the attached image). I think lab4d is using the same camera convention as colmap.

Intrinsics can be changed by editing config file `database/configs/$seqname.config`.

Let me know if you have additional questions.

![Screenshot_2024-05-04_17-02-15](https://github.com/lab4d-org/lab4d/assets/13134872/f1d740e5-2f87-4100-82f1-1eadea449c80)

**Comment by limaolin2017** [comment]
Thank you for your reply, I closed the issue.
