### ISSUE TITLE
[Bug/issue]About gauss_skin_consistency_loss

### ISSUE THREAD

**Issue by zz7379** [lab4d-org/lab4d#45]
Hi gengshan! Could you please explain the meaning of gauss_skin_consistency_loss? I don't fully understand your comment about it(Enforce consistency between the NeRF's SDF and the SDF of Gaussian bones). I would be grateful if you could provide me with the related papers! Thanks a lot!

**Comment by gengshan-y** [comment]
Sorry for the late response, Xinzhou. The goal of `gauss_skin_consistency_loss(...)` is to align the Gaussian bones (Bx6) with the object (represent by a density field), by minimizing their difference in density at sampled points.

This plays a similar role as the Sinkhorn divergence loss in BANMo.

**Comment by zz7379** [comment]
Understood. Thanks for your reply
