### ISSUE TITLE
[Bug/issue] Quality Difference Between BANMo and RAC in lab4d Testing

### ISSUE THREAD

**Issue by LyndzP** [lab4d-org/lab4d#46]
Hello lab4d team, I would like to express my gratitude for your ongoing project updates. I am currently testing BANMo  and Lab4d RAC version(skel-quad flag), and I've noticed a significant quality difference between them.

The two images below are of BANMo and skel-quad. As you can see, the skel-quad does not reconstruct the leg parts well. I referred to this link: https://lab4d-org.github.io/lab4d/tutorials/single_video_cat.html, but the results are not as expected.

Could I be missing something? I initially thought that RAC should deliver better results than BANMo. Could my assumption be incorrect? Thank you for taking the time to consider my query

## BANMo result
<img width="877" alt="스크린샷 2024-06-12 오후 4 58 24" src="https://github.com/lab4d-org/lab4d/assets/132452542/c4bd6c50-954f-402f-80d2-cee22f905d4f">

## lab4d skel-quad result
<img width="714" alt="스크린샷 2024-06-12 오후 5 01 50" src="https://github.com/lab4d-org/lab4d/assets/132452542/9d455d15-da95-492b-ae00-dec0bb1be654">

**Comment by gengshan-y** [comment]
Hi, this is not expected, 1) the result looks worse than what I would expect, and 2) skeleton should not lead to broken legs

Could you confirm whether the input is the `cat-pikachu-0` sequence, or the `cat-pikachu` dataset that contains 10 sequences?

And is the command to reproduce `bash scripts/train.sh lab4d/train.py 0 --seqname cat-pikachu-0 --logname fg-skel --fg_motion skel-quad`?

I will take a look and get back to you

**Comment by gengshan-y** [comment]
Hi @LyndzP, could you confirm what is your setup, e.g., whether this is single video input or multi-video input? 

From my end, results single video + `fg-motion=skel-quad` match the one on the tutorial page.

**Comment by LyndzP** [comment]
Hello @gengshan-y, thank you for taking the time to assist me. Here is my setup:
Additionally, here are the commands I've run from the beginning to the end.

- CPU : AMD Ryzen Threadripper PRO 5955WX 16-Cores
- GPU : NVIDIA GeForce RTX 4090 24GB
- CUDA : 11.8v

Also, I follow up to [Single videos tutorial](https://lab4d-org.github.io/lab4d/tutorials/single_video_cat.html)
```
> bash scripts/download_unzip.sh "https://www.dropbox.com/s/3w0vhh05olzwwn4/cat-pikachu.zip"
> wget https://www.dropbox.com/s/bgsodsnnbxdoza3/vcn_rob.pth -O ./preprocess/third_party/vcnplus/vcn_rob.pth
> wget https://www.dropbox.com/s/1464pg6c9ce8rve/quad.pth

> python scripts/run_preprocess.py cat-pikachu cat quad "0"
> bash scripts/train.sh lab4d/train.py 0 --seqname cat-pikachu-0 --logname fg-skel --fg_motion skel-quad

> python lab4d/export.py --flagfile=logdir/cat-pikachu-fg-skel/opts.log --load_suffix latest
```
Recently, I've been wondering if I might be downloading an older version of quad.pth or vcn_rob.pth.

**Comment by gengshan-y** [comment]
Hi, it shouldn't be related to quad.pth or vcn_rob.pth as they haven't been updated.

The steps you took look fine. Could you please share the log file so that I can take a look?

```
python scripts/zip_logdir.py logdir/cat-pikachu-0-fg-skel/
```
will zip the log for you

**Comment by LyndzP** [comment]
Hello, I've re-downloaded the project from Git and ran it again. Although the leg does appear, the quality is still not satisfactory. Here is the zip file. 
Additionally, following the multi-video processing tutorial resulted in no leg appearing, as shown in the photo above. I am attaching the zip file for this result as well. 

Thank you.

[single video processing zip file drive](https://drive.google.com/file/d/1_XC79H9qg7-EDwxS4DsqE-v9b3P9wtbI/view?usp=sharing)
[multi video processing zip file drive](https://drive.google.com/file/d/1K4X_OCZ5HI26Tc5yfJKEZNsoZEV-NAB8/view?usp=sharing)

**Comment by gengshan-y** [comment]
Hi, you may want to add `--num_rounds 120` to the training command. 

The result in the files you shared looks correct. The only gap is that the default is training for 20 rounds, which does not produce good surface. This is because [the annealing of the eikonal loss ](https://github.com/lab4d-org/lab4d/blob/d901fb98366a79ec00769ea7fa18547e8ca9c474/lab4d/engine/model.py#L124-L129)just finished at 20 rounds, and it needs some time to converge.

**Comment by LyndzP** [comment]
Now I can get better result both single and multi video 

Thank you very much for your kind explanation!
