### ISSUE TITLE
Camera Pose Initialization for category outside densepose

### ISSUE THREAD

**Issue by Batwho** [lab4d-org/lab4d#47]
Hello, I really appreciate this series of your work. I'm trying to apply this on customized videos. In the paper RAC, Appendix. B you mentioned a two-stage approach to register car videos.  Could you explain more about that part? Specifically, is there a code you already shared, and I might missed it? How can I do the same thing on a different category with videos? Thanks in advance.

**Comment by gengshan-y** [comment]
Hi, sorry for the late reply,

The goal of stage 1 is to train a pose network that takes an image as input, and produces a rough viewpoint estimation. Then we can use it to replace the quadruped/human viewpoint network,  and perform a standard lab4d optimization in stage 2.

This pose network is trained with manually labeled rotation/viewpoint ground-truth. The code to annotate GT viewpoint is implemented and the instruction can be found [here](https://lab4d-org.github.io/lab4d/tutorials/preprocessing.html#object-to-camera-transformations).

The code for training has not been integrated into lab4d. However, it should be doable to write a training script similar to [this](https://github.com/lab4d-org/lab4d/blob/f96d66afedd008976fdfc18fb50b4984bb454195/preprocess/scripts/canonical_registration.py#L124-L126), but changing the network from an MLP to the [viewpoint net](https://github.com/lab4d-org/lab4d/blob/f96d66afedd008976fdfc18fb50b4984bb454195/preprocess/scripts/canonical_registration.py#L92-L99).

Feel free to let me know if you encounter any difficulty.

**Comment by Batwho** [comment]
Thank you very much for your detailed explanation. I'm starting to work on this and understand everything until the last sentence. I assume you mean change this [mlp](https://github.com/lab4d-org/lab4d/blob/f96d66afedd008976fdfc18fb50b4984bb454195/preprocess/libs/torch_models.py#L25) to a viewpointnet. However, the viewpoint net you referred to also include a [densepose net](https://github.com/lab4d-org/lab4d/blob/f96d66afedd008976fdfc18fb50b4984bb454195/preprocess/third_party/viewpoint/dp_viewpoint.py#L311), which is used during inference time. 
Could you please show me how did you modify the viewpoint net for vehicle dataset to avoid using densepose net? It would be perfect if you could still find the training code when you did this experiment by any chance

**Comment by Batwho** [comment]
Accidentally closed

**Comment by gengshan-y** [comment]
Hi, the architecture of the viewpoint is [here](https://github.com/gengshan-y/rac/blob/0a5d4cca5037247228f6c2dd4a31d0e97de1ec89/nnutils/banmo.py#L580). 

[These arguments](https://github.com/gengshan-y/rac/blob/0a5d4cca5037247228f6c2dd4a31d0e97de1ec89/nnutils/banmo.py#L166C20-L168) are turned on when training feedforward models. Perhaps it is good to trace down the appearance of those flags to get a better picture of how is the training performed.

**Comment by Batwho** [comment]
Thank you so much for your help, I'm able to train the network.
