### ISSUE TITLE
[Bug/issue] Potenial bug in track_anything when working on multi-video of an object

### ISSUE THREAD

**Issue by ChaoyueSong** [lab4d-org/lab4d#50]
Hi @gengshan-y,

While preprocessing multiple videos for an object using the ```track_anything``` module, I encountered a potential bug in ```app.py``` at line 573.
   
    for path in tqdm(input_dir):
    ...

    size.append(original_size)
    
    videos = {}
    for id, input, output, osize in zip(uuids, input_dir, output_dir, size):
        videos[id] = {"input": input, "output": output, "size" : osize}

I think ```size.append(original_size)``` needs to be inside the for loop to ensure that the ```size``` list has the same length as ```uuids```, ```input_dir```, and ```output_dir``` when using ```zip```.

**Comment by gengshan-y** [comment]
Thanks for the report, it should be fixed.
