### ISSUE TITLE
About root pose and camera pose

### ISSUE THREAD

**Issue by s0rrymaker77777** [lab4d-org/lab4d#7]
Hi, thanks for your great work,

I want to ask about the difference between root pose and camera pose. For example, the rigid motion field in lab4d only has root body motion, will you also consider the camera pose separately for this rigid motion?

**Comment by gengshan-y** [comment]
Hi, we define a [`field2cam`](https://github.com/lab4d-org/lab4d/blob/a27a2d041719556e4e4846990f1d997d0c51f50d/lab4d/nnutils/nerf.py#L149-L151) separately for each neural field (background or object),

- for the background, it transforms 3D points from the scene coordinate to the camera coordinate. This is usually referred to as the camera pose  (`G_bg`, e.g. in colmap).
- for object fields, it transforms 3D points from the object coordinate to the camera coordinate. This is referred to as root pose (`G_obj`) in banmo. 
- To get the root pose wrt the background scene, one could use `G_bg^{-1}G_o`, as `X_bg = G_bg^{-1}G_o X_o`

**Comment by s0rrymaker77777** [comment]
Thanks so much for your reply, it helps a lot!
